
[/Script/CommonUI.CommonUISettings]
CommonButtonAcceptKeyHandling=TriggerClick

[ConsoleVariables]
CommonUI.CheckKeyboardFocusAndParentage=1
CommonUI.DisallowUserFocusedWidgetForPendingFocusRecipient=1
CommonUI.FallbackToDesiredOnAutoRestoreFailure=1

[/Script/EngineSettings.GeneralProjectSettings]
ProjectID=530D29B44E81BD291D41DEB937353092

[/Script/UnrealEd.ProjectPackagingSettings]
; 프로토타입 레벨 (스타팅 맵)
+DirectoriesToAlwaysCook=(Path="/Game/Prototype")
+MapsToCook=(FilePath="/Game/Prototype/L_FurnitureProto")

[/Script/CommonInput.CommonInputSettings]
InputData=/Game/Developers/MinkiCho/UI_Input/BP_CommonUIInputData.BP_CommonUIInputData_C
bEnableEnhancedInputSupport=True

